# -*- coding: utf-8 -*-
"""tnuos_streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1amJCGYMAk_kK2b-qRRUUutqZGuZ6OlgZ
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from fpdf import FPDF
import base64
from io import BytesIO

# Import our custom modules (Phase 2 & 3)
from tnuos_engine import calculate_portfolio_impact, determine_tcr_band
from scenario_manager import ScenarioModeler

# CONFIG & ASSETS

st.set_page_config(
    page_title="TNUoS 2026 Impact Calculator",
    page_icon="⚡",
    layout="wide"
)

# Hardcoded Centroids for DNO Zones (for the Heatmap)
ZONE_COORDS = {
    1:  {'lat': 57.1497, 'lon': -2.0943, 'name': 'Northern Scotland'},
    2:  {'lat': 55.8642, 'lon': -4.2518, 'name': 'Southern Scotland'},
    3:  {'lat': 54.9783, 'lon': -1.6178, 'name': 'Northern'},
    4:  {'lat': 53.4808, 'lon': -2.2426, 'name': 'North West'},
    5:  {'lat': 53.8008, 'lon': -1.5491, 'name': 'Yorkshire'},
    6:  {'lat': 53.1934, 'lon': -2.8931, 'name': 'N Wales & Mersey'},
    7:  {'lat': 52.9548, 'lon': -1.1581, 'name': 'East Midlands'},
    8:  {'lat': 52.4862, 'lon': -1.8904, 'name': 'Midlands'},
    9:  {'lat': 52.6309, 'lon': 1.2974,  'name': 'Eastern'},
    10: {'lat': 51.4816, 'lon': -3.1791, 'name': 'South Wales'},
    11: {'lat': 51.2787, 'lon': 0.5217,  'name': 'South East'},
    12: {'lat': 51.5074, 'lon': -0.1278, 'name': 'London'},
    13: {'lat': 51.4543, 'lon': -0.9781, 'name': 'Southern'},
    14: {'lat': 50.7184, 'lon': -3.5339, 'name': 'South Western'},
}

# HELPER FUNCTIONS

def create_pdf_report(summary_stats, opportunities_df):
    """Generates a PDF summary of the risk analysis."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="TNUoS 2026 Risk Assessment", ln=1, align='C')
    pdf.ln(10)

    # Executive Summary
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Executive Summary", ln=1)
    pdf.set_font("Arial", size=11)

    baseline = summary_stats['baseline_cost']
    forecast = summary_stats['forecast_cost']
    increase = forecast - baseline
    pct = (increase / baseline * 100) if baseline > 0 else 0

    pdf.cell(200, 8, txt=f"Total Portfolio Cost (2025/26): GBP {baseline:,.2f}", ln=1)
    pdf.cell(200, 8, txt=f"Forecast Portfolio Cost (2026/27): GBP {forecast:,.2f}", ln=1)
    pdf.cell(200, 8, txt=f"Net Increase: GBP {increase:,.2f} (+{pct:.1f}%)", ln=1)
    pdf.cell(200, 8, txt=f"Sites Flagged 'Critical Risk' (>100% Rise): {summary_stats['high_risk_count']}", ln=1)

    pdf.ln(10)

    # Opportunities
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Optimization Opportunities (Band Drops)", ln=1)
    pdf.set_font("Arial", size=10)

    if not opportunities_df.empty:
        for index, row in opportunities_df.iterrows():
            line = f"Site: {row['site_id']} | Reduce Capacity by {row['reduction_kVA']} kVA to drop Band."
            pdf.cell(200, 8, txt=line, ln=1)
    else:
        pdf.cell(200, 8, txt="No immediate band-drop opportunities identified.", ln=1)

    return pdf.output(dest='S').encode('latin-1')

# UI LAYOUT

st.title("⚡ TNUoS 2026 Impact Calculator")
st.markdown("### Strategic Non-Commodity Pricing Tool")

# Sidebar for global controls
with st.sidebar:
    st.header("Project Controls")
    analysis_mode = st.radio("Select Module:", ["Single Site Calculator", "Portfolio Analytics"])

    st.info("""
    **Context:**
    The April 2026 RIIO-T3 Price Control will double fixed residual charges.
    Use this tool to quantify exposure.
    """)

# MODULE 1: SINGLE SITE CALCULATOR

if analysis_mode == "Single Site Calculator":
    st.subheader("Quick Quote: Single Site Impact")

    col1, col2, col3 = st.columns(3)

    with col1:
        s_volt = st.selectbox("Voltage Level", ["LV", "HV", "EHV"])
        s_zone = st.selectbox("DNO Zone", list(range(1, 15)), format_func=lambda x: f"{x} - {ZONE_COORDS[x]['name']}")

    with col2:
        s_type = st.selectbox("Meter Type", ["HH", "NHH"])
        s_cap = st.number_input("Agreed Capacity (kVA)", min_value=0, value=100)

    with col3:
        s_cons = st.number_input("Annual Consumption (kWh)", min_value=0, value=50000)

    if st.button("Calculate Impact"):
        # Create 1-row DataFrame
        single_site = pd.DataFrame([{
            'site_id': 'Quick_Quote_Site',
            'voltage_level': s_volt,
            'dno_zone': s_zone,
            'meter_type': s_type,
            'agreed_capacity_kva': s_cap,
            'annual_consumption_kwh': s_cons
        }])

        # Run Engines for 2025 and 2026
        res_2025 = calculate_portfolio_impact(single_site, target_year=2025)
        res_2026 = calculate_portfolio_impact(single_site, target_year=2026)

        cost_25 = res_2025['total_tnuos_cost'].values[0]
        cost_26 = res_2026['total_tnuos_cost'].values[0]
        band = res_2026['tcr_band'].values[0]

        # Display Metrics
        m1, m2, m3 = st.columns(3)
        m1.metric("TCR Band", band)
        m2.metric("2025 Baseline Cost", f"£{cost_25:,.2f}")
        m3.metric("2026 Forecast Cost", f"£{cost_26:,.2f}", delta=f"{(cost_26-cost_25):,.2f}", delta_color="inverse")

        st.warning(f"Note: This site is classified as **{band}**. The fixed daily charge for this band increases significantly in April 2026.")

# MODULE 2: PORTFOLIO ANALYTICS

elif analysis_mode == "Portfolio Analytics":
    st.subheader("Portfolio Risk Dashboard")

    # File Uploader
    uploaded_file = st.file_uploader("Upload Portfolio CSV", type=['csv'])

    # Template Download
    if not uploaded_file:
        st.info("Upload a CSV with columns: `site_id`, `voltage_level`, `agreed_capacity_kva`, `dno_zone`, `meter_type`, `annual_consumption_kwh`")
        # Create a dummy CSV for user to download as template
        dummy = pd.DataFrame({
            'site_id': ['Site_A', 'Site_B'],
            'voltage_level': ['LV', 'HV'],
            'agreed_capacity_kva': [100, 500],
            'dno_zone': [12, 3],
            'meter_type': ['HH', 'HH'],
            'annual_consumption_kwh': [0, 0]
        })
        csv = dummy.to_csv(index=False).encode('utf-8')
        st.download_button("Download Template CSV", csv, "portfolio_template.csv", "text/csv")

    else:
        # 1. LOAD AND PROCESS
        df_sites = pd.read_csv(uploaded_file)

        # Scenario Toggle: Fixed vs Pass-Through
        st.divider()
        col_t1, col_t2 = st.columns([1, 2])
        with col_t1:
            contract_type = st.radio("Contract Structure Scenario", ["Pass-Through (Exposure)", "Fixed (Shielded)"])

        # Calculation
        with st.spinner('Running Calculation Engine...'):
            df_2025 = calculate_portfolio_impact(df_sites, target_year=2025)
            df_2026 = calculate_portfolio_impact(df_sites, target_year=2026)
            df_2030 = calculate_portfolio_impact(df_sites, target_year=2030) # Future view

        # Calculate Deltas
        total_2025 = df_2025['total_tnuos_cost'].sum()
        total_2026 = df_2026['total_tnuos_cost'].sum()
        total_2030 = df_2030['total_tnuos_cost'].sum()

        # Apply Fixed Contract Logic
        if contract_type == "Fixed (Shielded)":
            # If fixed, the 'Cost to Customer' in 2026 remains at 2025 levels (simplified)
            # The 'Exposure' is hidden.
            display_total_2026 = total_2025
            delta_msg = "Shielded (No Change)"
            delta_val = 0
        else:
            display_total_2026 = total_2026
            delta_msg = "Direct Exposure"
            delta_val = total_2026 - total_2025

        # --- KPI ROW ---
        kpi1, kpi2, kpi3, kpi4 = st.columns(4)
        kpi1.metric("Sites Analyzed", len(df_sites))
        kpi2.metric("2025/26 Annual Budget", f"£{total_2025:,.0f}")
        kpi3.metric("2026/27 Forecast", f"£{display_total_2026:,.0f}", delta=f"{((display_total_2026-total_2025)/total_2025)*100:.1f}%")

        # Count >100% Increases (Risk Score)
        # We compare 2026 unshielded vs 2025 to find structural risk, regardless of contract
        risk_df = df_2026.copy()
        risk_df['cost_2025'] = df_2025['total_tnuos_cost']
        risk_df['pct_change'] = ((risk_df['total_tnuos_cost'] - risk_df['cost_2025']) / risk_df['cost_2025']) * 100
        high_risk_count = len(risk_df[risk_df['pct_change'] > 100])

        kpi4.metric("High Risk Sites (>100% Rise)", high_risk_count, delta_color="inverse")

        # --- WATERFALL CHART ---
        st.subheader("Cost Waterfall: The Structural Shift")

        # Prepare Data for Waterfall
        # Steps: 2025 Base -> Residual Price Rise -> Locational Change -> 2026 Total
        res_diff = df_2026['residual_cost_pound'].sum() - df_2025['residual_cost_pound'].sum()
        loc_diff = df_2026['locational_cost_pound'].sum() - df_2025['locational_cost_pound'].sum()

        fig_waterfall = go.Figure(go.Waterfall(
            name = "20", orientation = "v",
            measure = ["relative", "relative", "relative", "total", "total"],
            x = ["2025 Baseline", "Fixed Residual Hike", "Locational/Other", "2026 Forecast", "2030 Projection"],
            textposition = "outside",
            text = [f"£{total_2025/1000:.1f}k", f" +£{res_diff/1000:.1f}k", f" +£{loc_diff/1000:.1f}k", f"£{total_2026/1000:.1f}k", f"£{total_2030/1000:.1f}k"],
            y = [total_2025, res_diff, loc_diff, total_2026, total_2030],
            connector = {"line":{"color":"rgb(63, 63, 63)"}},
        ))
        fig_waterfall.update_layout(title = "Profit Impact Bridge (GBP)", showlegend = False)
        st.plotly_chart(fig_waterfall, use_container_width=True)

        # --- TABS FOR DEEP DIVE ---
        tab1, tab2, tab3 = st.tabs(["🌍 Geographic Map", "📉 Sensitivity & Optimization", "📑 Reports"])

        with tab1:
            st.markdown("### Regional Exposure Heatmap")
            # Map Data Preparation
            map_data = df_2026.groupby('dno_zone').agg({
                'total_tnuos_cost': 'sum',
                'site_id': 'count'
            }).reset_index()

            # Add Lat/Lon
            map_data['lat'] = map_data['dno_zone'].map(lambda x: ZONE_COORDS.get(x, {}).get('lat', 54.0))
            map_data['lon'] = map_data['dno_zone'].map(lambda x: ZONE_COORDS.get(x, {}).get('lon', -2.0))
            map_data['zone_name'] = map_data['dno_zone'].map(lambda x: ZONE_COORDS.get(x, {}).get('name', 'Unknown'))

            # Map Visual
            fig_map = px.scatter_mapbox(
                map_data, lat="lat", lon="lon", size="total_tnuos_cost", color="total_tnuos_cost",
                hover_name="zone_name", zoom=4.5, mapbox_style="carto-positron",
                title="TNUoS Cost Exposure by Region (Bubble Size = Cost)",
                color_continuous_scale=px.colors.sequential.Bluered
            )
            st.plotly_chart(fig_map, use_container_width=True)

        with tab2:
            st.markdown("### Scenario Modeling")

            # 1. Sensitivity Analysis
            st.write("**Sensitivity Analysis: Demand Variation**")
            sens_slider = st.slider("Adjust Consumption/Capacity by %", -20, 20, 0)

            if sens_slider != 0:
                # Modifying the dataframe in memory for the 'What-If'
                df_sens = df_sites.copy()
                factor = 1 + (sens_slider / 100)
                df_sens['annual_consumption_kwh'] = df_sens['annual_consumption_kwh'] * factor
                df_sens['agreed_capacity_kva'] = (df_sens['agreed_capacity_kva'] * factor).astype(int)

                res_sens = calculate_portfolio_impact(df_sens, target_year=2026)
                sens_total = res_sens['total_tnuos_cost'].sum()

                diff = sens_total - total_2026
                st.metric("New 2026 Forecast", f"£{sens_total:,.0f}", delta=f"£{diff:,.0f}")

                if abs(diff) < (total_2026 * 0.01) and abs(sens_slider) > 5:
                    st.warning("⚠️ Insight: Changing volume has minimal impact on cost. This indicates your portfolio is heavily exposed to **Fixed Residual Charges**, not consumption.")

            st.divider()

            # 2. Optimization Engine (Band Drop)
            st.write("**Optimization Opportunities: Band Management**")
            modeler = ScenarioModeler(df_sites)
            opportunities = modeler.identify_band_drop_opportunities()

            if not opportunities.empty:
                st.success(f"Found {len(opportunities)} sites where small capacity reduction drops a Band.")
                st.dataframe(opportunities)
            else:
                st.info("No immediate 'Band Drop' opportunities found within 15% threshold.")

        with tab3:
            st.markdown("### Export Reports")

            # Generate PDF
            if st.button("Generate Executive Summary PDF"):
                # Prepare summary stats
                stats = {
                    'baseline_cost': total_2025,
                    'forecast_cost': total_2026,
                    'high_risk_count': high_risk_count
                }
                # Use modeler to get opps for the report
                mod = ScenarioModeler(df_sites)
                opps = mod.identify_band_drop_opportunities()

                pdf_bytes = create_pdf_report(stats, opps)

                b64 = base64.b64encode(pdf_bytes).decode()
                href = f'<a href="data:application/octet-stream;base64,{b64}" download="TNUoS_Risk_Report.pdf">Download PDF Report</a>'
                st.markdown(href, unsafe_allow_html=True)